Repository kiali/kiali.io, pull requests merged in 2020-07, with the labels that each got.

#259 Fix filtering on listing page
  themes/kiali/layouts/_default/list.html.html
Labels: bug

#261 Add graph op node feature
  content/documentation/edge/features/index.adoc
  static/images/documentation/features/graph-operations-thumb.png
  static/images/documentation/features/graph-operations.png
Labels: team/saturn

#264 Force presence of a table of contents on faq pages
  themes/kiali/layouts/faq/list.html
Labels: bug, team/saturn

#262 FAQ to explain how to get a token
  content/documentation/edge/faq/authentication/index.adoc
  content/documentation/edge/faq/authentication/token-strategy.adoc
Labels: team/saturn

#260 Add a manual release for v1.20.0
  content/documentation/latest
  content/documentation/v1.20/_index.adoc
  content/documentation/v1.20/architecture.adoc
  content/documentation/v1.20/developer-api/.gitignore
  content/documentation/v1.20/developer-api/index.html
  content/documentation/v1.20/distributed-tracing/index.adoc
  content/documentation/v1.20/extensions/index.adoc
  content/documentation/v1.20/faq/_index.adoc
  content/documentation/v1.20/faq/distributed-tracing/certificate-unknown-authority.adoc
  content/documentation/v1.20/faq/distributed-tracing/index.adoc
  content/documentation/v1.20/faq/distributed-tracing/no-embedded-feature.adoc
  content/documentation/v1.20/faq/distributed-tracing/no-tracing-about-modal.adoc
  content/documentation/v1.20/faq/distributed-tracing/see-url-about-modal.adoc
  content/documentation/v1.20/faq/distributed-tracing/temporarily-down.adoc
  content/documentation/v1.20/faq/distributed-tracing/turn-off-jaeger-integration.adoc
  content/documentation/v1.20/faq/general/how-can-i-get-in-touch.adoc
  content/documentation/v1.20/faq/general/how-contribute.adoc
  content/documentation/v1.20/faq/general/how-do-i-access-kiai.adoc
  content/documentation/v1.20/faq/general/index.adoc
  content/documentation/v1.20/faq/general/internet-explorer.adoc
  content/documentation/v1.20/faq/general/kiali-does-not-work.adoc
  content/documentation/v1.20/faq/general/what-are-minimum-rbac-privileges.adoc
  content/documentation/v1.20/faq/general/what-is-the-license.adoc
  content/documentation/v1.20/faq/graph/external-https-as-tcp.adoc
  content/documentation/v1.20/faq/graph/graph-badly-laid-out.adoc
  content/documentation/v1.20/faq/graph/index.adoc
  content/documentation/v1.20/faq/graph/many-unknown.adoc
  content/documentation/v1.20/faq/graph/missing-edges.adoc
  content/documentation/v1.20/faq/graph/no-traffic-leaving-mesh.adoc
  content/documentation/v1.20/faq/graph/passthrough-traffic.adoc
  content/documentation/v1.20/faq/graph/service-rt.adoc
  content/documentation/v1.20/faq/graph/unexpected-service-nodes.adoc
  content/documentation/v1.20/faq/validations/host-format.adoc
  content/documentation/v1.20/faq/validations/index.adoc
  content/documentation/v1.20/features/index.adoc
  content/documentation/v1.20/glossary/_index.adoc
  content/documentation/v1.20/glossary/concepts/index.adoc
  content/documentation/v1.20/glossary/networking/index.adoc
  content/documentation/v1.20/glossary/observability/index.adoc
  content/documentation/v1.20/installation-guide/index.adoc
  content/documentation/v1.20/quick-start/index.adoc
  content/documentation/v1.20/runtimes-monitoring/index.adoc
  content/documentation/v1.20/validations/index.adoc
Labels: team/saturn

#265 Point Makefile to correct version
  Makefile
Labels: bug, team/saturn

#266 Point latest to v1.21
  content/documentation/latest
Labels: bug, team/saturn

#267 Release Notes 1.21.0
  content/news/release-notes.adoc
Labels: team/saturn

#269 update sprint vids 42/41/40
  themes/kiali/layouts/partials/home/video-sprint-demo-section.html
Labels: team/saturn

#268 updates for helm
  content/documentation/edge/installation-guide/index.adoc
  content/documentation/edge/quick-start/index.adoc
Labels: team/saturn
